M48
; DRILL file {KiCad 8.0.7} date 2025-03-06T17:29:40-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-06T17:29:40-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X8.6909Y-3.1311
X8.6909Y-3.3587
T2
X7.7392Y-3.7596
X7.8892Y-3.7596
M30
