#define MICROPY_HW_BOARD_NAME "Battery Board"
#define MICROPY_HW_MCU_NAME "rp2040"
// External flash MR2xH40 MRAM
#define EXTERNAL_FLASH_QSPI_SINGLE
#define EXTERNAL_FLASH_NO_JEDEC


#define BOARD_FLASH_SIZE (FLASH_SIZE - 0x4000 - CIRCUITPY_INTERNAL_NVM_SIZE)

#define CIRCUITPY_DRIVE_LABEL "FLIGHT CONTROLLER BOARD V1a"
#define CIRCUITPY_BOOT_COUNTER 1

#define BOARD_HAS_CRYSTAL 1

#define MICROPY_HW_NEOPIXEL (&pin_GPIO24)

#define DEFAULT_I2C_BUS_SDA (&pin_GPIO2)
#define DEFAULT_I2C_BUS_SCL (&pin_GPIO3)

#define DEFAULT_UART_BUS_TX (&pin_GPIO0)
#define DEFAULT_UART_BUS_RX (&pin_GPIO1)

#define DEFAULT_SPI_BUS_SCK (&pin_GPIO18)
#define DEFAULT_SPI_BUS_MOSI (&pin_GPIO19)
#define DEFAULT_SPI_BUS_MISO (&pin_GPIO16)
